name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    name: Build Windows Debug
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
  
    - name: Generate solution
      run: ./GenerateSolution.bat
      
    - name: Build Solution (windows)
      run: |
        cd Generated
        MSBuild.exe "RESweet.sln" -m -property:Configuration=Debug
    
    - name: Run tests
      timeout-minutes: 5
      run: ./Build/Bin/Debug/RECore_Tests.exe
